{% set version = "0.3.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-academictwitter
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/academictwitteR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/academictwitteR/academictwitteR_{{ version }}.tar.gz
  sha256: 1cfefca891c7e56a3c94c5b8c7443af1070ae2c22cf1ed7f896a45f19007b614

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr >=1.0.0
    - r-httr
    - r-jsonlite
    - r-lubridate
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-tibble
    - r-tidyr
    - r-tidyselect
    - r-usethis
  run:
    - r-base
    - r-dplyr >=1.0.0
    - r-httr
    - r-jsonlite
    - r-lubridate
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-tibble
    - r-tidyr
    - r-tidyselect
    - r-usethis

test:
  commands:
    - $R -e "library('academictwitteR')"           # [not win]
    - "\"%R%\" -e \"library('academictwitteR')\""  # [win]

about:
  home: https://github.com/cjbarrie/academictwitteR
  license: MIT
  summary: Package to query the Twitter Academic Research Product Track (<https://developer.twitter.com/en/solutions/academic-research>), providing access to full-archive search and other v2 API endpoints. Functions are written with academic research in mind. They provide flexibility in how the user wishes to store collected
    data, and encourage regular storage of data to mitigate loss when collecting large volumes of tweets. They also provide workarounds to manage and reshape the format in which data is provided on the client side.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
